# install and configure cloudstack management node
- name: Ensure Apache CloudStack management packages are installed and present
  apt:
    name: cloudstack-management
    update_cache: true

# TODO: this is not an ansible module, so it will be rerun everytime called in
#   deployment.  So might be good to detect if already done and skip?
# Usage: cloudstack-setup-databases user:[password]@mysqlhost:[port] [--deploy-as=rootuser:[rootpassword]] [--auto=/path/to/server-setup.xml] [-e ENCRYPTIONTYPE] [-m MGMTSECRETKEY] [-k DBSECRETKEY] [-g ENCRYPTORVERSION] [--debug]
#
#  -m MGMTSECRETKEY, --managementserver-secretkey=MGMTSECRETKEY
#                        Secret key used to encrypt confidential parameters in
#                        db.properties. A string, default is password
#  -k DBSECRETKEY, --database-secretkey=DBSECRETKEY
#                        Secret key used to encrypt sensitive database values.
#                        A string, default is password
#  -i MSHOSTIP, --mshost=MSHOSTIP
#                        Cluster management server host IP. A string, by
#                        default it will try to detect a local IP
- name: Setup the cloudstack database
  command: cloudstack-setup-databases cloud:{{ mysql_cloud_password }}@localhost --deploy-as=root:{{ mysql_root_password }}  -m {{ management_secret_key }} -k {{ database_secret_key }} -i {{ cloud_manager_ip }}

- name: Setup the cloudstack manager
  command: cloudstack-setup-management

