# roles and configurations common to all cloudstack nodes in this cloud
- hosts: manager database agent
  vars_files:
    - vars/globals.yml
  roles:
    - node
    - network
    - cloudstackrepo

# the database role configurs host that run the cloudstack mysql database
- hosts: database
  vars_files:
    - vars/globals.yml
    - vars/secrets.yml
  roles:
    - database

# the manager role configures host that act as the cloudstack manager
- hosts: manager
  vars_files:
    - vars/globals.yml
    - vars/secrets.yml
  roles:
    - manager
    - seedstorage

# the agent role configures hosts that act as cloudstack compute nodes agents

