# before ansible management can proceed smoothly using injected ssh keys, need
# to get the ssh management keys into all hosts that will be used in the cloudstack
- hosts: all
  vars_files:
    - vars/globals.yml
  vars:
    ansible_user: "{{ insertion_user }}"
    ansible_ssh_pass: "{{ insertion_password }}"
    ansible_become_pass: "{{ insertion_password }}"
  roles:
    - ansiblesshmanage
    
# roles and configurations common to all cloudstack nodes in this cloud
- hosts: manager database agent
  vars_files:
    - vars/globals.yml
  roles:
    - node
    - network
    - cloudstackrepo

# the database role configures host that run the cloudstack mysql database
- hosts: database
  vars_files:
    - vars/globals.yml
    - vars/secrets.yml
  roles:
    - database

# the manager role configures host that act as the cloudstack manager
- hosts: manager
  vars_files:
    - vars/globals.yml
    - vars/secrets.yml
  roles:
    - manager
    - seedstorage

# the agent role configures hosts that act as cloudstack compute nodes agents
- hosts: agent
  vars_files:
    - vars/globals.yml
    - vars/secrets.yml
  roles:
    - agent
