# gather the keys from all cloudstack management servers locally to this ansible management node
# TODO: in future if want to have multipe HA managers, will need to modify to support
#   downloading and injecting multiple cloudstack management keys
- hosts: manager
  tasks:
    - name: Fetch the management key from cloudstack manager to a local file on ansible manager
      fetch:
        src: "/var/lib/cloudstack/management/.ssh/id_rsa.pub"
        dest: "keys/manager-id_rsa.pub"
        flat: true

# now distribute keys to all cloudstack aganets
- hosts: agent
  tasks:
    - name: Copy cloudstack management key from ansible manager buffer to the agent node
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'keys/manager-id_rsa.pub') }}"

# a bit of a kludge, but we can try and killall of the processes still hanging around for
# the cloudstack user before we attempt to remove the user
# ensure the cloudstack user has been removed from nodes
- hosts: manager agent database
  tasks:
    - name: Kill all cloudstack processes so no error when we remove the user NOTE: this is likely to fail here as cloudstack acces has probably timed out now
      command: killall -u cloudstack -w
      ignore_errors: true
      
    - name: Remove temporary cloudstack users
      user:
        name: cloudstack
        groups: cloudstack
        state: absent
        remove: yes

# setup cloudmonkey for command line admin tasks
- hosts: manager
  tasks:
    - name: Install cloudmonkey command line admin tool on the manager
      get_url:
        url: https://github.com/apache/cloudstack-cloudmonkey/releases/download/6.3.0/cmk.linux.x86-64
        dest:  /usr/local/bin/cmk
        mode: u+x
      
    - name: Call cloud monkey sync to load apis and enable for initial use
      command: cmk sync
