# Make sure node package list is updated and all packages upgraded
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

# basic security, remove temporary user, tighten up sshd access to this node
# TODO: This is no longer working because before this we login withthe cloudstack
#   user to inject our ssh keys.  Apparently there are still user processes hanging
#   around.  Need to force them to be cleaned up, or maybe we could move this to
#   setup, though it really belongs here.
- name: Kill all cloudstack processes so we don't error when we remove the user
  command: killall -u cloudstack -w
  ignore_errors: true

- name: Remove temporary cloudstack users
  user:
    name: cloudstack
    groups: cloudstack
    state: absent
    remove: yes
  ignore_errors: true
    
- name: Ensure ansible management server is only allowed host
  lineinfile:
    path: /etc/hosts.allow
    regexp: '^sshd:.*'
    line: "sshd: {{ ansible_manager_ip }} {{ cloud_manager_ip }}"
    state: present

- name: Ensure all other hosts are denied ssh access
  lineinfile:
    path: /etc/hosts.deny
    regexp: '^sshd:.*'
    line: 'sshd: ALL'
    state: present


# disable passwords and password auth and only allow ssh auth
- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication.*'
    line: 'PasswordAuthentication no'

- name: Enable only ssh public key authentication to host
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication.*'
    line: 'PubkeyAuthentication yes'

- name: Also don't allow PAM (password auth module?)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'UsePAM.*'
    line: 'UsePAM no'

- name: Make sure if we are going to use root, we cannot ssh in using password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#PermitRootLogin.*'
    line: 'PermitRootLogin prohibit-password'

    
- name: Restart sshd
  service:
    name: sshd
    state: restarted

# setup server time sync and time zone
- name: Set timezone to America/Chicago
  timezone:
    name: America/Chicago

- name: Install chrony for server time synchronization
  apt:
    name: chrony
    state: present
  
- name: Restart chrony service to ensure time is being synchronized and enable the service on reboot
  service:
    name: chrony
    state: restarted
    enabled: yes
  
# miscellaneous, add aliases and other things to make command line admin easier
- name: Create common aliases for administrators
  template: src=bash_aliases.j2 dest=/root/.bash_aliases
