# Make sure node package list is updated and all packages upgraded
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

# basic security, remove temporary user, tighten up sshd access to this node
- name: Remove temporary cloudstack users
  user:
    name: cloudstack
    groups: cloudstack
    state: absent
    remove: yes

- name: Ensure ansible management server is only allowed host
  lineinfile:
    path: /etc/hosts.allow
    regexp: '^sshd:.*'
    line: 'sshd: {{ management_ip }}'
    state: present

- name: Ensure all other hosts are denied ssh access
  lineinfile:
    path: /etc/hosts.deny
    regexp: '^sshd:.*'
    line: 'sshd: ALL'
    state: present

    
- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication.*'
    line: 'PasswordAuthentication no'

- name: Enable only ssh public key authentication to host
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication.*'
    line: 'PubkeyAuthentication yes'
    
- name: Restart sshd
  service:
    name: sshd
    state: restarted

# setup server time sync and time zone
- name: Set timezone to America/Chicago
  timezone:
    name: America/Chicago

- name: Install chrony for server time synchronization
  apt:
    name: chrony
    state: present
  
- name: Restart chrony service to ensure time is being synchronized and enable the service on reboot
  service:
    name: chrony
    state: restarted
    enabled: yes
  
# miscellaneous, add aliases and other things to make command line admin easier
- name: Create common aliases for administrators
  template: src=bash_aliases.j2 dest=/root/.bash_aliases
