# Make sure node package list is updated and all packages upgraded
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Ensure ansible management server is only allowed host
  lineinfile:
    path: /etc/hosts.allow
    regexp: '^sshd:.*'
    line: "sshd: {{ ansible_manager_ip }} {{ cloud_manager_ip }}"
    state: present

- name: Ensure all other hosts are denied ssh access
  lineinfile:
    path: /etc/hosts.deny
    regexp: '^sshd:.*'
    line: 'sshd: ALL'
    state: present


# disable passwords and password auth and only allow ssh auth
- name: Enable only ssh public key authentication to host
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication.*'
    line: 'PubkeyAuthentication yes'

# our goal is to disable any keyboard password authentication and lock
# passwords for the cloudstack and root accounts.  We need to leave
# PAM on, but make sure PasswordAuthentication and
# KbdInteractiveAuthentication are off to achieve this
- name: We actually need PAM still enabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'UsePAM.*'
    line: 'UsePAM yes'

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication.*'
    line: 'PasswordAuthentication no'

- name: Disable keyboard interactive password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^.*KbdInteractiveAuthentication.*'
    line: 'KbdInteractiveAuthentication no'

    
- name: Make sure if we are going to use root, we cannot ssh in using password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#PermitRootLogin.*'
    line: 'PermitRootLogin prohibit-password'

- name: Disable cloudstack password, so only ssh authentication can work
  user:
    name: cloudstack
    password_lock: true

- name: Disable root password, so only ssh authentication can work
  user:
    name: root
    password_lock: true
    
- name: Restart sshd
  service:
    name: sshd
    state: restarted


# setup server time sync and time zone
- name: Set timezone to America/Chicago
  timezone:
    name: America/Chicago

- name: Install chrony for server time synchronization
  apt:
    name: chrony
    state: present
  
- name: Restart chrony service to ensure time is being synchronized and enable the service on reboot
  service:
    name: chrony
    state: restarted
    enabled: yes
  
# miscellaneous, add aliases and other things to make command line admin easier
- name: Create common aliases for administrators
  template: src=bash_aliases.j2 dest=/root/.bash_aliases
