# Global variables used over all roles and tasks for
# cloudstack ansible deployments in this project

# The ip address of management machine
# TODO: could/should we get these, especially our cloud manager ips, through introspection or
#  ansible facts?
ansible_manager_ip: 192.168.0.9
cloud_manager_ip: 192.168.0.3

# the specific version of cloudstack management and agent being setup
cloudstack_version: 4.18
cloudstack_system_kvm_url: http://download.cloudstack.org/systemvm/{{ cloudstack_version }}/systemvmtemplate-{{ cloudstack_version }}.0-kvm.qcow2.bz2
  
# The cloud database server node machine name, this machine runs the
# mysql database and is connected by management and agent
cloud_database: cloud01

# secondary storage nfs information, used when seeding system VM template
nfs_server_ip: 192.168.0.2
tmp_nfs_path: /mnt/secondary
secondary_nfs_path: /export/secondary
