# Global variables used over all roles and tasks for
# cloudstack ansible deployments in this project

# The ip address of management machine
# TODO: could/should we get these, especially our cloud manager ips, through introspection or
#  ansible facts?
ansible_manager_ip: 192.168.0.9
cloud_manager_ip: 192.168.0.3

# Network configuration for cloud nodes
dns_addresses_ip: "8.8.8.8,8.8.4.4"
default_router_ip: 192.168.0.1
cloudbr1_vlan_number: 739
network_mtu: 1500

# the specific version of cloudstack management and agent being setup
cloudstack_version: 4.18
cloudstack_system_kvm_url: http://download.cloudstack.org/systemvm/{{ cloudstack_version }}/systemvmtemplate-{{ cloudstack_version }}.0-kvm.qcow2.bz2

# initial host access information, before ssh insertion
insertion_user: cloudstack
insertion_password: cloudstack

# The cloud database server node machine name, this machine runs the
# mysql database and is connected by management and agent
cloud_database: cloud01

# secondary storage nfs information, used when seeding system VM template
nfs_server_ip: 192.168.0.2
tmp_nfs_path: /mnt/secondary
secondary_nfs_path: /export/secondary

# TODO: for the moment we will just set an explicit variable to
#   detect if running deploy a subsequent time, so that we
#   can skip over tasks that should not be done a second time
#   and are not ansible idemopotent.
# So for now, deploy should be true if this is the first deployment,
# and false if want/need to rerun deployment to skip some
# non idemopotent tasks.
deploy: true


# cloudstack infrastructure
# The following are used when configuring the default cloudstack infrastructure.
# TODO: perhaps these should be in a separate file.

# zone configuration
zone_name: Zone1
dns1: 8.8.8.8
dns2: 8.8.4.4
internal_dns1: 8.8.8.8
internal_dns2: 8.8.4.4
guest_cidr_address: "10.1.1.0/24"
network_type: Advanced

# physical network configuration
physical_network_name: "Physical Network 1"
vlan: "100-200"
isolation_method: VLAN

# guest network configuration
network_name: "HarterHouseNet"
network_display_text: "Harter Household Cloud Network"
network_cidr: "10.1.1.0/24"
network_gateway: "10.1.1.1"
network_netmask: "255.255.255.0"
network_offering: "DefaultIsolatedNetworkOfferingWithSourceNatService"

# pod configuration
pod_name: "Pod-Zone1"
pod_gateway: "192.168.0.1"
pod_netmask: "255.255.255.0"
pod_start_ip: "192.168.0.201"
pod_end_ip: "192.168.0.254"

# vlan ip range? for physical network ip assignments of virtual network gateways?
vlan_start_ip: "192.168.0.154"
vlan_end_ip: "192.168.0.200"

# cluster configuration
cluster_name: "Cluster-Zone1"
hypervisor: "KVM"
cluster_type: "CloudManaged"

# storage pool configuration
primary_name: "Primary1"
primary_ip: 192.168.0.2
primary_path: /export/primary
primary_url: "nfs://{{ primary_ip }}{{ primary_path }}"

secondary_name: "Secondary1"
secondary_ip: 192.168.0.2
secondary_path: /export/secondary
secondary_url: "nfs://{{ secondary_ip }}{{ secondary_path }}"
secondary_scope: "ZONE"
secondary_provider: "NFS"
