# Secrets used in cloudstack deployment
# These are mostly passwords used by database, keystores, etc.
# This file is excluded from the repository, we need to create/
# generate these secrets before cloudstack deployment
# TODO: ultimately have option to randomly generate these secrets

# cloudstack mysql root user password
mysql_root_password: Cl0ud5tack

# cloudstack mysql cloud user password  
mysql_cloud_password: Cl0ud5tack

# cloudstack management server secret encryption key
management_secret_key: Cl0ud5tack

# cloudstack mysql database secret encryption key
database_secret_key: Cl0ud5tack

