# first we will copy cloudstack management key to the insertion user using the
# insertion password
- name: Copy ansible management key from ansible manager to insertion user on new host
  authorized_key:
    user: "{{ insertion_user }}"
    state: present
    key: "{{ lookup('file', 'keys/ansiblemanagement.key.pub') }}"

# the insertion user should have sudo privileges, so copy the keys from the insertion user
# to the root user now
- name: Copy the ansible management key from ansible to the root account
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'keys/ansiblemanagement.key.pub') }}"
  become: true
  

